services:
  - type: web
    name: bukuya-sacco
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_8plJ6WeCVuix@ep-old-field-axh8l81l-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: ADMIN_USERNAME
        value: manager
      - key: ADMIN_PASSWORD
        value: Manager@2026
      - key: PYTHON_VERSION
        value: 3.11.8
